# Generated by Django 5.0.1 on 2024-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.FileField(default=1, upload_to='static/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='actor',
            field=models.CharField(max_length=64),
        ),
    ]
