# Generated by Django 5.0.1 on 2024-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_image_alter_review_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('crime', '범죄'), ('sf', 'SF'), ('comedy', '코미디'), ('romance', '로맨스'), ('thrill', '스릴러'), ('war', '전쟁'), ('horror', '공포'), ('else', '기타')], default='else', max_length=10),
        ),
    ]
